# Generated by Django 5.0.1 on 2024-02-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0005_rename_total_benifits_employee_total_benefits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(max_length=255),
        ),
    ]
