# Generated by Django 5.0.1 on 2024-02-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0006_alter_employee_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_name',
            field=models.CharField(max_length=25),
        ),
    ]
