# Generated by Django 5.0.1 on 2024-02-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0011_alter_employee_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.TextField(max_length=255),
        ),
    ]
